### ISSUE TITLE
Cartes manquantes ?

### ISSUE THREAD

**Issue by Niarks** [PierrePlaziat/MaGeek#1]
Bonjour cher ami d'Alexandre,

J'ai testé ton soft pour la gestion et création de decks pour le jeu Magic the Gathering.

J'ai simplement voulu créer un nouveau deck et y mettre une carte, j'ai choisi au hasard "Jwari Disruption", mais malheureusement aucune carte n'est apparue en résultat de la recherche.

Y aurait-il une limitation sur les extensions disponibles ?

En tout cas joli travail.

Bonne journée.

Laurent.

**Comment by PierrePlaziat** [comment]
Bonjour,

Merci pour ton retour, 
ce n'est effectivement pas tres parlant tel quel:
Il faut d'abord importer des cartes dans la base de donnée locale via la recherche, 
les filtres en dessous ne voient que les cartes deja ajoutées.

Normalement toutes les extensions doivent y etre,

**Comment by Niarks** [comment]
C'est bon, j'ai trouvé d'où venait le soucis
![Mageek](https://user-images.githubusercontent.com/7194488/178781902-87715fe8-e69d-4b63-bdce-c977b0a3b8e3.jpg)
.
