### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Niarks** [PierrePlaziat/MaGeek#2]
Bonjour,

J'ai installé le soft sur mon pc fixe perso et il ne fonctionne plus.

1. J'ai dl le .msi
2. J'ai installé le soft dans un répertoire différent de celui par défaut
3. Je lance le soft et je remarque déjà que je n'ai pas les propositions de decks
4. Je crée un nouveau deck dont je cahnge le nom
5. Je le sélectionne dans la liste en haut à gauche via un simple clic
6. Fermeture du soft

Voici une petite vidéo du souci https://youtu.be/Koe8QccQtX0

A bientôt.

Laurent.

**Comment by PierrePlaziat** [comment]
Bonjour,
Merci pour ce retour.

Ce que tu appelles propositions de decks sont en fait le produit de mes importations de test, 
j'ai volontairement vidé la DB avant la generation d'un nouvel installeur, je suis en train de mettre en place un system d'importation plus commode.

Effectivement il me semble que j'ai viré ce bug depuis, ce doit être un null exception puisque le deck est vide. Peut etre qu'en passant par l'importation de texte tu pourrais obtenir un deck avec au moins une carte et contourner le bug?

Par contre pour le moment je suis en grand chantier donc la prochaine version mettra un peu de temps a paraitre mais sera j'espere plus "production ready".

**Comment by PierrePlaziat** [comment]
Nouvelle version dispo

**Comment by PierrePlaziat** [comment]
Desormais, il n'y aura plus d'installeur, ce sera la release portable presente ici qui fera foi:
https://github.com/PierrePlaziat/MaGeek/releases
